### ISSUE TITLE
use case: web desktop

### ISSUE THREAD

**Issue by milahu** [podium-lib/podlet#327]
this project looks underrated ... whats the catch?

this looks like the perfect framework for building a web desktop

- process isolation
- support all frameworks
- run devservers in webworkers = selfhosted development

> building a web desktop

examples

- https://github.com/os-js/OS.js
- https://github.com/dahliaOS/pangolin_desktop
- https://github.com/puruvj/macos-web
- https://github.com/blueedgetechno/win11React
- https://github.com/DustinBrett/daedalOS
- https://github.com/Renovamen/playground-macos
- https://github.com/vivek9patel/vivek9patel.github.io

i just would need a window manager, with tiling and floating layouts

- https://github.com/golden-layout/golden-layout
- https://github.com/bimdata/areas

**Comment by milahu** [comment]
> this project looks underrated ... whats the catch?

- https://github.com/topics/micro-frontend
- https://github.com/topics/microfrontend
- https://github.com/umijs/qiankun - 14K stars
- https://github.com/neuland/micro-frontends - 4K stars - https://micro-frontends.org/ - Techniques, strategies and recipes for building a modern web app with multiple teams using different JavaScript frameworks

**Comment by digitalsadhu** [comment]
Hey! Don’t think we’ve ever considered the use case. The project enjoys a good amount of usage across our companies apps but we don’t really know much about who is using it further afield. It’s under steady development but since it’s stable, changes tend to be fairly small. We don’t spend much of any time promoting it. Desktop apps sound like a fun area to explore. Can’t see why it wouldn’t be a good fit now that you mention it.

**Comment by milahu** [comment]
> since it’s stable, changes tend to be fairly small. We don’t spend much of any time promoting it

makes sense
i was just surprised that this project has just 100 stars
but then i found the plenthora of similar projects in https://github.com/topics/micro-frontend

nitpick: web-desktop != desktop-app
the beauty of web-desktop is that users dont need to install anything ...
no "npm install", no electron ... just click and run
persistence via indexeddb ...
optionally, users can install as browser app, so it also works offline

currently im exploring a micro-frontend based on qwik
i hope that qwik has better SSR performance than other frameworks (solid, svelte, ...)
https://github.com/BuilderIO/qwik/issues/1604#issuecomment-1329511233

my project is https://github.com/milahu/browserforge
