### ISSUE TITLE
SSC and layout scope

### ISSUE THREAD

**Issue by achrafsoltani** [podium-lib/podlet#377]
Hello, 

I have a question, not sure if this is the right place to do so :

What should be considered best practice, 
- using the same layout script to do server side composition for multiple routes
- creating a script per route which will end up with having multiple layout apps running.

In the following snippet :

```
const podlet = layout.client.register({
    name: 'myPodlet', // required
    uri: 'http://localhost:7100/manifest.json', // required
});
```

Shouldn't the Podlet be created independentl of the layout, then be registered on multiple layout objects to allow multi-page composition ? 

Thanks

**Comment by wkillerud** [comment]
Hello @achrafsoltani

> Shouldn't the Podlet be created independentl of the layout, then be registered on multiple layout objects to allow multi-page composition ?

A single layout object can serve multiple routes. This type of setup is perfectly valid:

```js
app.get(layout.pathname(), async (req, res) => {
  res.podiumSend(`<!-- page HTML content -->`);
});

app.get(`${layout.pathname()}/view/:id`, async (req, res) => {
  res.podiumSend(`<!-- other page HTML content -->`);
});

app.get(`${layout.pathname()}/new`, async (req, res) => {
  res.podiumSend(`<!-- other page HTML content -->`);
});
```

With this, you can register all podlets on the same layout instance, and in the route handlers fetch the podlets you need for that page.

![multi-page-application](https://github.com/podium-lib/podlet/assets/1223410/ee2c5600-5527-4d02-9f27-995ae53946ad)

> creating a script per route which will end up with having multiple layout apps running.

This sounds like something similar to sharding per route.

You can consider this approach if one or more routes will get more traffic and need to scale independently of others. Or if you want to deploy one part of the site independently. In this case it's not only a new instance of the `Layout`, but it's a whole separate app.

You don't need to create a new `Layout` instance per route in the same application. In that case, prefer the example above with one `Layout`, multiple routes.

![sharded-application-by-load](https://github.com/podium-lib/podlet/assets/1223410/fa593bd9-9714-4b5d-859f-c9c4c26b2fb1)

**Comment by achrafsoltani** [comment]
Awesome, very elaborate, thank you.
