### ISSUE TITLE
Podlet doesn't set `Content-Type: text/html`

### ISSUE THREAD

**Issue by wkillerud** [podium-lib/podlet#442]
After https://github.com/podium-lib/podlet/commit/815ea97df599676a6a1dd56dd6aeef4f91b27c95 the response from the podlet doesn't include the `Content-Type` response header.

[res.send added it for us before](https://expressjs.com/en/4x/api.html#res.send), but after replacing it with `write` + `end` we dropped this header. The communication with layouts still seem to work OK, but a user reported this broke one of their tests (they were looking for this header).

**Comment by digitalsadhu** [comment]
This does turn out to be important. If you test the podlet directly without explicitly setting the content type you end up getting html text.
